### ISSUE TITLE
How do you re-render?

### ISSUE THREAD

**Issue by seanhess** [omniscientjs/omniscient-react-router#1]
I'm getting this all working together right now, thanks for the example!

How do you re-render when a immstruct changes with this integration?

Thanks,
~sean

**Comment by seanhess** [comment]
Got it working! New version of react-router is much easier to work with than the last. I'd recommend updating this repo with something canonical.

https://gist.github.com/seanhess/2925452e7f0bf29865d2

**Comment by torgeir** [comment]
You don't, yet ;) 

just started looking into this myself, and things seem to have changed https://github.com/rackt/react-router/issues/28

PRs welcome!

**Comment by torgeir** [comment]
Alright, nice. Had a go somewhat similar to yours, and that seems to work quite nicely!

Though personally I think I'd prefer the previous versions' approach by passing individual props to different `Route`s. 

Currently all routes would have access to _one_ shared state. Making things work by splitting the state up seem unnecessarily difficult, and needs some wrapper react component that closes over a cursor, much like with your 'page()' function, but it seems we'll have to live with that:)

Can multiple routers coexist within a single page?

**Comment by torgeir** [comment]
Does this really work like you'd intend? If you pass

```
<Handler one={state_one} two={state_two}/>
```

https://gist.github.com/seanhess/2925452e7f0bf29865d2#file-omni-react-js-L86

all your components have `one` and `two` on their props

**Comment by seanhess** [comment]
I don't know how else to do it. Are there other options?

**Comment by torgeir** [comment]
Oh, you're right, I didn't think this through. Here's an updated example with different cursors (that could reside in different immstructs), and passing route-data as statics

https://github.com/omniscientjs/react-router-omniscient-example/blob/master/index.js

**Comment by torgeir** [comment]
[omniscient/issues/25](https://github.com/omniscientjs/omniscient/issues/25) moved here:

> Hmm. Having to switch the cursor based on the url feels really broken to me. Is there any way to specify the cursor on the route definition?
> 
> Or maybe there's some way to let the page components choose their own
> cursor.

That was merely an example to show it's possilble pass different cursors to different components based on what's rendered. 

Here's how react-router suggest you [handle async data](https://github.com/rackt/react-router/blob/master/examples/async-data/app.js#L122-L138). A similar approach ought to work with async/cursors as well

**Comment by mikaelbr** [comment]
Did we ever conclude this? Closable? cc @torgeir

**Comment by torgeir** [comment]
Well, we got the example repo. It's clumsy, to say the least, with the latest react router api not taking handler props, could prob need more experimentation
