### ISSUE TITLE
router doesn't work when data is at rest

### ISSUE THREAD

**Issue by darkone23** [omniscientjs/omniscient-react-router#3]
For some reason the routes aren't working in the example if you comment out the following lines:

``` js
setInterval(_ => data.cursor().update('even', m => m + 2), 100);
setInterval(_ => data.cursor().update('odd',  n => n + 2), 100);
```

Without those two lines (that is, when the immstruct is at rest and not changing) the routes do nothing.

It looks like this might be related to: https://github.com/rackt/react-router/issues/470

**Comment by torgeir** [comment]
I've updated the example to show how this can be done in https://github.com/omniscientjs/omniscient-react-router/commit/412c0ff855d54256d0a59f4845581217bbef74d5 without the interval-data-updates. See a more [in depth explanation of how why this works](https://github.com/omniscientjs/omniscient/issues/109#issuecomment-120509946).
